version: 0.1

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm ci
  build:
    command:
      - npm run build
  post_build:
    command:
      - npm run start:prod
artifacts:
  files:
    - '**/*'
